server:
  port: 8880

# 配置文件里，设置key=value的值，用@Value去获取
test:
  hello: Hello11113

# mybatis接口映射resources下的xml文件
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

# spring数据库连接
spring:
  datasource:
#    url: jdbc:mysql://rm-bp18c3t29i08j9kb35o.mysql.rds.aliyuncs.com/wiki?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    url: jdbc:mysql://rm-bp18c3t29i08j9kb35o.mysql.rds.aliyuncs.com/wiki-dev?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: mostroot
    password: Ssl@13639120050
    driver-class-name: com.mysql.cj.jdbc.Driver
